# Generated by Django 4.2.7 on 2025-04-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_microempresa_integral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microempresasatelite',
            name='capacidad_produccion',
        ),
        migrations.RemoveField(
            model_name='microempresasatelite',
            name='maquinas',
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='microempresasatelite',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('tipo_servicio', models.CharField(choices=[('CONFECCION', 'Confección'), ('ARREGLO', 'Arreglo'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('microempresa_satelite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.microempresasatelite')),
            ],
        ),
    ]
