# Generated by Django 4.2.7 on 2025-04-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_microempresasatelite_capacidad_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('INTEGRAL', 'Microempresa Integral'), ('SATELITE', 'Microempresa Satélite'), ('ADMIN', 'Administrador'), ('SYSTEM_ADMIN', 'Administrador del Sistema')], max_length=12),
        ),
    ]
