# Generated by Django 4.2.7 on 2025-04-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='microempresaintegral',
            name='eslogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microempresaintegral',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
        migrations.AddField(
            model_name='microempresaintegral',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=100),
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='eslogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
        migrations.AddField(
            model_name='microempresasatelite',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=100),
        ),
    ]
