# Generated by Django 4.2.7 on 2025-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Cantidad de unidades del servicio solicitadas'),
        ),
    ]
